[project]
name = "option"
version = "0.1.0"
description = "Scala Option in Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
